- pages/_document.js
- styles/globals.css
- tailwind.config.js
> Extend tailwind with the required colors and fonts

- tailwind.config.js
> make tailwind colors extend the actual colors instead of overwrite them

- components/CommentList.js
- pages/setpage.js
- users.json
> implement the set page

- .eslintrc.json
- pages/search/[search].js
- yarn.lock
> Fix deployment failing due to wrong import

- components/Navbar.js
> fix navbar button styles

- firebase.js
- package.json
- pages/new.js
- store/index.js
- store/sets/setsSlice.js
- yarn.lock
> create actions to create set for redux

- pages/register.js
- pages/signin.js
- store/user/userSlice.js
> redirect the user to home page when they login

- pages/register.js
- pages/signin.js
- store/user/userSlice.js
> reverted userSlice.js

- store/user/userSlice.js
> add the new created users information into the users collection

- pages/404.js
> fix the width of the 404 page

- components/CarouselCard.js
- components/SetCarousel.js
- hooks/useCarouselEditor.js
> fix bug where flashcards content don't render correctly in SetCarousel

- components/Card.js
- components/Navbar.js
- pages/_app.js
- pages/library.js
- pages/new.js
- store/sets/setsSlice.js
- store/user/userSlice.js
> connect my library page with firebase

- components/Card.js
- pages/_app.js
- pages/setpage/[setId].js
- store/sets/setsSlice.js
> fix setpage route and connect it to the store

- components/Loading.js
- pages/home.js
- pages/library.js
- pages/new.js
- pages/profile/[userId].js
- pages/register.js
- pages/signin.js
- pages/test.js
Fixes #98
You can check it on the `/test` page
> Create loading indicator component

- components/Navbar.js
- store/user/userSlice.js
> Add signout option to the navbar component

- components/NewSetForm.js
- sets.js
> update the category list in the NewSetForm component

- pages/new.js
> restrict the new page if the user isn't logged in

- pages/search/[search].js
> connect search page with firebase

- pages/_app.js
> get user's library sets after loggin in

- pages/home.js
> use the set's card images and avatars in the home page

- pages/new.js
- pages/search/[search].js
> remove h1 loading tag from new page, and delete console log from search page
